# This describes a pod that will run the nginx. 
# The container is made using the nginx:1.21.3 image.

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21.3
    ports:
    - containerPort: 80
